#! /bin/bash

# Config
DATASET=15mrad_002_master.h5
HOST=127.0.0.1
PORT=8008

# Commands
if [ -n $1 ]; then
    if [ $1 == "default" ]; then
        export AS_HDF5_MASTER_FILE=ansto_simplon_api/master_file_examples/example_1_master.h5
    else
        export AS_HDF5_MASTER_FILE=$1
    fi
else
    export AS_HDF5_MASTER_FILE=data/$DATASET
fi


uvicorn ansto_simplon_api.main:app --host $HOST --port $PORT 